const { pool } = require("../config/db");

const bannedPatterns = [
  /\b(insert|update|delete|drop|truncate|alter|create|grant|revoke)\b/i,
  /--/,
  /\/\*/,
];

function validateSql(sql) {
  if (!sql || typeof sql !== "string") {
    throw new Error("Empty SQL generated by LLM.");
  }
  const normalized = sql.trim();
  if (!normalized.toLowerCase().startsWith("select")) {
    throw new Error("Only SELECT queries are allowed.");
  }
  if (normalized.split(";").filter(Boolean).length > 1) {
    throw new Error("Multiple statements are not allowed.");
  }
  for (const pattern of bannedPatterns) {
    if (pattern.test(normalized)) {
      throw new Error("Unsafe SQL detected.");
    }
  }
}

async function executeReadOnlyQuery(sql) {
  validateSql(sql);
  const [rows] = await pool.query(sql);
  return rows;
}

module.exports = {
  executeReadOnlyQuery,
  validateSql,
};
